config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :data_kontak
  get 'data_kontak/index'
  root 'data_kontak#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action :create, :read, :update, :destroy, :index, :to => :crud

    if user.role == 'adm'
      can :manage, :all
    elsif user.role == 'usr'
      can :manage, DataKontak, user_id: user.id
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_kontak.rb
class DataKontak < ApplicationRecord
  belongs_to :user, :dependent => :delete
  validates_associated :user
  validates :nama, presence: { message: 'Tidak Boleh Kosong' }
  validates :no_telp, presence: { message: 'Tidak Boleh Kosong' }, numericality: { only_integer: true, message: 'Harus Angka' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :data_kontak, :dependent => :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  after_action :store_action

  def store_action
    return unless request.get?
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?)
        store_location_for(:user, data_kontak_index_path)
    end
  end
end

app/controllers/data_kontak_controller.rb
class DataKontakController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @kontaks = DataKontak.accessible_by(current_ability)
  end

  def edit
    @kontak = DataKontak.find(params[:id])
  end

  def new
    @kontak = DataKontak.new
  end

  def update
    @kontak = DataKontak.find(params[:id])
    respond_to do |format|
      if @kontak.update(kontak_params)
        format.html { redirect_to root_path }
        format.js { render js: "window.location='#{root_path}'" }
      else
        format.html { render 'edit' }
        format.js
      end
    end
  end

  def create
    @kontak = current_user.data_kontak.new(kontak_params)
    respond_to do |format|
      if @kontak.save
        format.html { redirect_to root_path }
        format.js { render js: "window.location='#{root_path}'" }
      else
        format.html { render 'new' }
        format.js
      end
    end
  end

  def destroy
    @kontak = DataKontak.find(params[:id])
    @kontak.destroy
    redirect_to root_path
  end

  private
    def kontak_params
      params.require(:kontak).permit(:nama, :alamat, :no_telp, :almt_email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_kontak_helper.rb
module DataKontakHelper
end

app/views/data_kontak/_edit.html.erb
<%= form_for :kontak, url: data_kontak_path(@kontak), method: :patch, remote: true do |f| %>
  <div class="modal fade" id="edit-modal" tabindex="-1" role="dialog" style="display: block">
    <div class="modal-dialog">
      <div class="loginmodal-container">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2>Edit Kontak</h2>
          <div id=error_edit></div>
        </div>
        <%= f.text_field :nama %>
        <%= f.text_field :no_telp %>
        <%= f.text_field :alamat %>
        <%= f.email_field :almt_email %>
        <%= f.submit "Simpan", class: 'login loginmodal-submit' %>
      </div>
    </div>
  </div>
<% end %>

app/views/data_kontak/_error_state.html.erb
<% if @kontak.errors.any? %>
  <div class="alert alert-danger">
    <h3>
      <%= @kontak.errors.count %>
      kesalahan input:
    </h3>
    <ul>
      <% @kontak.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/data_kontak/_new.html.erb
<%= form_for :kontak, url: data_kontak_index_path, remote: true do |f| %>
  <div class="modal fade" id="form-modal" tabindex="-1" role="dialog" style="display: none">
    <div class="modal-dialog">
      <div class="loginmodal-container">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2>Kontak Baru</h2>
          <div id=error_statement></div>
        </div>
        <%= f.text_field :nama, placeholder: "Nama" %>
        <%= f.text_field :no_telp, placeholder: "No Telepon" %>
        <%= f.text_field :alamat, placeholder: "Alamat" %>
        <%= f.email_field :almt_email, placeholder: "Email" %>
        <%= f.submit "Simpan", class: 'login loginmodal-submit' %>
      </div>
    </div>
  </div>
<% end %>

app/views/data_kontak/create.js.erb
$("#error_statement").html("<%= escape_javascript (render 'error_state') %>")

app/views/data_kontak/edit.js.erb
$("#edit-form").html("<%= escape_javascript (render 'edit') %>")
$("#edit-modal").modal("show")

app/views/data_kontak/index.html.erb
<div class="container">
  <h2><%= current_user.email %></h2>
  <table class="table -table-hover">
    <thead>
      <tr>
        <th>Nama</th>
        <th>Alamat</th>
        <th>No Telepon</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @kontaks.each do |kontak| %>
        <tr>
          <td><%= kontak.nama %></td>
          <td><%= kontak.alamat %></td>
          <td><%= kontak.no_telp %></td>
          <td><%= kontak.almt_email %></td>
          <td><%= link_to 'Edit', edit_data_kontak_path(kontak), class: 'btn btn-primary', remote: true %>
          <%= link_to 'Hapus', data_kontak_path(kontak), class: 'btn btn-primary', method: :delete,
          data: { confirm: 'Are You Sure?'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/data_kontak/new.js.erb
$("#form-baru").html("<%= escape_javascript (render 'new' ) %>");
$("#form-modal").modal("show");

app/views/data_kontak/update.js.erb
$("#error_edit").html("<%= escape_javascript (render 'error_state') %>")

app/views/layouts/_intro.html.erb
<div class="page-header">
  <h1>Phone Book</h1>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--a class="navbar-brand" href="index">Phone Book</a-->
      <% if user_signed_in? %>
        <%= link_to 'Phone Book', data_kontak_index_path , class: 'navbar-brand' %>
      <% else %>
        <%= link_to 'Phone Book', root_path, class: 'navbar-brand'%>
      <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_registration_path %>
          <li><%= link_to 'New Contact', new_data_kontak_path, remote: true %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewPhonebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |key, value| %>
      <div class="alert alert=<%= key %>">
        <%= value %>
      </div>
      <% end %>
    </div>
    <div class="container">
      <%= render 'layouts/intro' %>
    </div>
    <%= yield %>
    <div id="form-baru"></div>
    <div id="tampil-form"></div>
    <div id="edit-form"></div>
  </body>
</html>